// source: https://www.kaggle.com/datasets/thedevastator/mars-weather-data-from-2012-to-2018
export default [
    {
        id: '541',
        terrestrial_date: '2014-04-14',
        sol: 600,
        ls: 116,
        season: 'Month 4',
        min_temp: -81,
        max_temp: -25,
        pressure: 787,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '543',
        terrestrial_date: '2014-04-13',
        sol: 599,
        ls: 115,
        season: 'Month 4',
        min_temp: -84,
        max_temp: -20,
        pressure: 788,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '542',
        terrestrial_date: '2014-04-12',
        sol: 598,
        ls: 115,
        season: 'Month 4',
        min_temp: -84,
        max_temp: -25,
        pressure: 787,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '540',
        terrestrial_date: '2014-04-11',
        sol: 597,
        ls: 114,
        season: 'Month 4',
        min_temp: -84,
        max_temp: -26,
        pressure: 790,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '539',
        terrestrial_date: '2014-04-10',
        sol: 596,
        ls: 114,
        season: 'Month 4',
        min_temp: -82,
        max_temp: -24,
        pressure: 791,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '538',
        terrestrial_date: '2014-04-09',
        sol: 595,
        ls: 113,
        season: 'Month 4',
        min_temp: -83,
        max_temp: -25,
        pressure: 792,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '537',
        terrestrial_date: '2014-04-08',
        sol: 594,
        ls: 113,
        season: 'Month 4',
        min_temp: -83,
        max_temp: -22,
        pressure: 793,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '536',
        terrestrial_date: '2014-04-07',
        sol: 593,
        ls: 112,
        season: 'Month 4',
        min_temp: -83,
        max_temp: -23,
        pressure: 795,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '534',
        terrestrial_date: '2014-04-06',
        sol: 592,
        ls: 112,
        season: 'Month 4',
        min_temp: -83,
        max_temp: -26,
        pressure: 795,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '533',
        terrestrial_date: '2014-04-05',
        sol: 591,
        ls: 111,
        season: 'Month 4',
        min_temp: -82,
        max_temp: -26,
        pressure: 795,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '535',
        terrestrial_date: '2014-04-04',
        sol: 590,
        ls: 111,
        season: 'Month 4',
        min_temp: -82,
        max_temp: -26,
        pressure: 797,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '531',
        terrestrial_date: '2014-04-03',
        sol: 589,
        ls: 110,
        season: 'Month 4',
        min_temp: -85,
        max_temp: -27,
        pressure: 798,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '532',
        terrestrial_date: '2014-04-02',
        sol: 588,
        ls: 110,
        season: 'Month 4',
        min_temp: -84,
        max_temp: -24,
        pressure: 799,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '530',
        terrestrial_date: '2014-04-01',
        sol: 587,
        ls: 109,
        season: 'Month 4',
        min_temp: -85,
        max_temp: -28,
        pressure: 801,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '529',
        terrestrial_date: '2014-03-31',
        sol: 586,
        ls: 109,
        season: 'Month 4',
        min_temp: -82,
        max_temp: -24,
        pressure: 802,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '527',
        terrestrial_date: '2014-03-30',
        sol: 585,
        ls: 109,
        season: 'Month 4',
        min_temp: -83,
        max_temp: -26,
        pressure: 802,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '528',
        terrestrial_date: '2014-03-29',
        sol: 584,
        ls: 108,
        season: 'Month 4',
        min_temp: -82,
        max_temp: -25,
        pressure: 804,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '526',
        terrestrial_date: '2014-03-28',
        sol: 583,
        ls: 108,
        season: 'Month 4',
        min_temp: -82,
        max_temp: -27,
        pressure: 806,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '525',
        terrestrial_date: '2014-03-27',
        sol: 582,
        ls: 107,
        season: 'Month 4',
        min_temp: -84,
        max_temp: -27,
        pressure: 807,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '524',
        terrestrial_date: '2014-03-26',
        sol: 581,
        ls: 107,
        season: 'Month 4',
        min_temp: -84,
        max_temp: -28,
        pressure: 808,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '523',
        terrestrial_date: '2014-03-25',
        sol: 580,
        ls: 106,
        season: 'Month 4',
        min_temp: -83,
        max_temp: -24,
        pressure: 810,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '522',
        terrestrial_date: '2014-03-24',
        sol: 579,
        ls: 106,
        season: 'Month 4',
        min_temp: -82,
        max_temp: -22,
        pressure: 811,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '521',
        terrestrial_date: '2014-03-22',
        sol: 578,
        ls: 105,
        season: 'Month 4',
        min_temp: -83,
        max_temp: -23,
        pressure: 812,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '519',
        terrestrial_date: '2014-03-21',
        sol: 577,
        ls: 105,
        season: 'Month 4',
        min_temp: -84,
        max_temp: -27,
        pressure: 813,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '520',
        terrestrial_date: '2014-03-20',
        sol: 576,
        ls: 104,
        season: 'Month 4',
        min_temp: -84,
        max_temp: -26,
        pressure: 815,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '518',
        terrestrial_date: '2014-03-19',
        sol: 575,
        ls: 104,
        season: 'Month 4',
        min_temp: -82,
        max_temp: -26,
        pressure: 816,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '517',
        terrestrial_date: '2014-03-18',
        sol: 574,
        ls: 103,
        season: 'Month 4',
        min_temp: -85,
        max_temp: -23,
        pressure: 817,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '516',
        terrestrial_date: '2014-03-17',
        sol: 573,
        ls: 103,
        season: 'Month 4',
        min_temp: -84,
        max_temp: -27,
        pressure: 819,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '514',
        terrestrial_date: '2014-03-16',
        sol: 572,
        ls: 102,
        season: 'Month 4',
        min_temp: -85,
        max_temp: -27,
        pressure: 820,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '515',
        terrestrial_date: '2014-03-15',
        sol: 571,
        ls: 102,
        season: 'Month 4',
        min_temp: -84,
        max_temp: -26,
        pressure: 821,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '513',
        terrestrial_date: '2014-03-14',
        sol: 570,
        ls: 102,
        season: 'Month 4',
        min_temp: -84,
        max_temp: -26,
        pressure: 823,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '512',
        terrestrial_date: '2014-03-13',
        sol: 569,
        ls: 101,
        season: 'Month 4',
        min_temp: -85,
        max_temp: -27,
        pressure: 825,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '511',
        terrestrial_date: '2014-03-12',
        sol: 568,
        ls: 101,
        season: 'Month 4',
        min_temp: -86,
        max_temp: -28,
        pressure: 825,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '510',
        terrestrial_date: '2014-03-11',
        sol: 567,
        ls: 100,
        season: 'Month 4',
        min_temp: -86,
        max_temp: -28,
        pressure: 827,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '507',
        terrestrial_date: '2014-03-10',
        sol: 566,
        ls: 100,
        season: 'Month 4',
        min_temp: -86,
        max_temp: -27,
        pressure: 829,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '508',
        terrestrial_date: '2014-03-09',
        sol: 565,
        ls: 99,
        season: 'Month 4',
        min_temp: -85,
        max_temp: -27,
        pressure: 830,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '509',
        terrestrial_date: '2014-03-08',
        sol: 564,
        ls: 99,
        season: 'Month 4',
        min_temp: -86,
        max_temp: -27,
        pressure: 831,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '505',
        terrestrial_date: '2014-03-07',
        sol: 563,
        ls: 98,
        season: 'Month 4',
        min_temp: -87,
        max_temp: -31,
        pressure: 833,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '506',
        terrestrial_date: '2014-03-06',
        sol: 562,
        ls: 98,
        season: 'Month 4',
        min_temp: -85,
        max_temp: -23,
        pressure: 834,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '504',
        terrestrial_date: '2014-03-05',
        sol: 561,
        ls: 97,
        season: 'Month 4',
        min_temp: -85,
        max_temp: -23,
        pressure: 835,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '503',
        terrestrial_date: '2014-03-04',
        sol: 560,
        ls: 97,
        season: 'Month 4',
        min_temp: -86,
        max_temp: -23,
        pressure: 836,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '502',
        terrestrial_date: '2014-03-03',
        sol: 559,
        ls: 96,
        season: 'Month 4',
        min_temp: -85,
        max_temp: -27,
        pressure: 838,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '500',
        terrestrial_date: '2014-03-02',
        sol: 558,
        ls: 96,
        season: 'Month 4',
        min_temp: -85,
        max_temp: -26,
        pressure: 839,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '498',
        terrestrial_date: '2014-03-01',
        sol: 557,
        ls: 96,
        season: 'Month 4',
        min_temp: -85,
        max_temp: -29,
        pressure: 840,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '501',
        terrestrial_date: '2014-02-28',
        sol: 556,
        ls: 95,
        season: 'Month 4',
        min_temp: -85,
        max_temp: -29,
        pressure: 842,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '499',
        terrestrial_date: '2014-02-27',
        sol: 555,
        ls: 95,
        season: 'Month 4',
        min_temp: -85,
        max_temp: -31,
        pressure: 843,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '497',
        terrestrial_date: '2014-02-26',
        sol: 554,
        ls: 94,
        season: 'Month 4',
        min_temp: -84,
        max_temp: -22,
        pressure: 843,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '496',
        terrestrial_date: '2014-02-25',
        sol: 553,
        ls: 94,
        season: 'Month 4',
        min_temp: -84,
        max_temp: -26,
        pressure: 845,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '493',
        terrestrial_date: '2014-02-24',
        sol: 552,
        ls: 93,
        season: 'Month 4',
        min_temp: -86,
        max_temp: -29,
        pressure: 847,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '495',
        terrestrial_date: '2014-02-23',
        sol: 551,
        ls: 93,
        season: 'Month 4',
        min_temp: -85,
        max_temp: -28,
        pressure: 848,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '494',
        terrestrial_date: '2014-02-22',
        sol: 550,
        ls: 92,
        season: 'Month 4',
        min_temp: -85,
        max_temp: -27,
        pressure: 850,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '492',
        terrestrial_date: '2014-02-21',
        sol: 549,
        ls: 92,
        season: 'Month 4',
        min_temp: -87,
        max_temp: -23,
        pressure: 851,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '491',
        terrestrial_date: '2014-02-20',
        sol: 548,
        ls: 91,
        season: 'Month 4',
        min_temp: -86,
        max_temp: -28,
        pressure: 852,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '488',
        terrestrial_date: '2014-02-19',
        sol: 547,
        ls: 91,
        season: 'Month 4',
        min_temp: -85,
        max_temp: -29,
        pressure: 853,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '489',
        terrestrial_date: '2014-02-18',
        sol: 546,
        ls: 91,
        season: 'Month 4',
        min_temp: -85,
        max_temp: -34,
        pressure: 855,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '490',
        terrestrial_date: '2014-02-17',
        sol: 545,
        ls: 90,
        season: 'Month 4',
        min_temp: -85,
        max_temp: -29,
        pressure: 856,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '487',
        terrestrial_date: '2014-02-16',
        sol: 544,
        ls: 90,
        season: 'Month 4',
        min_temp: -86,
        max_temp: -27,
        pressure: 857,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '486',
        terrestrial_date: '2014-02-15',
        sol: 543,
        ls: 89,
        season: 'Month 3',
        min_temp: -84,
        max_temp: -26,
        pressure: 858,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '477',
        terrestrial_date: '2014-02-13',
        sol: 542,
        ls: 89,
        season: 'Month 3',
        min_temp: -85,
        max_temp: -28,
        pressure: 859,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '482',
        terrestrial_date: '2014-02-12',
        sol: 541,
        ls: 88,
        season: 'Month 3',
        min_temp: -84,
        max_temp: -27,
        pressure: 861,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '481',
        terrestrial_date: '2014-02-11',
        sol: 540,
        ls: 88,
        season: 'Month 3',
        min_temp: -84,
        max_temp: -29,
        pressure: 862,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '476',
        terrestrial_date: '2014-02-10',
        sol: 539,
        ls: 87,
        season: 'Month 3',
        min_temp: -85,
        max_temp: -23,
        pressure: 864,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '472',
        terrestrial_date: '2014-02-09',
        sol: 538,
        ls: 87,
        season: 'Month 3',
        min_temp: -85,
        max_temp: -25,
        pressure: 865,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '469',
        terrestrial_date: '2014-02-08',
        sol: 537,
        ls: 86,
        season: 'Month 3',
        min_temp: -83,
        max_temp: -28,
        pressure: 865,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '470',
        terrestrial_date: '2014-02-07',
        sol: 536,
        ls: 86,
        season: 'Month 3',
        min_temp: -83,
        max_temp: -29,
        pressure: 867,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '468',
        terrestrial_date: '2014-02-06',
        sol: 535,
        ls: 86,
        season: 'Month 3',
        min_temp: -88,
        max_temp: -29,
        pressure: 868,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '467',
        terrestrial_date: '2014-02-05',
        sol: 534,
        ls: 85,
        season: 'Month 3',
        min_temp: -86,
        max_temp: -29,
        pressure: 869,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '466',
        terrestrial_date: '2014-02-04',
        sol: 533,
        ls: 85,
        season: 'Month 3',
        min_temp: -87,
        max_temp: -30,
        pressure: 871,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '464',
        terrestrial_date: '2014-02-03',
        sol: 532,
        ls: 84,
        season: 'Month 3',
        min_temp: -88,
        max_temp: -23,
        pressure: 872,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '465',
        terrestrial_date: '2014-02-02',
        sol: 531,
        ls: 84,
        season: 'Month 3',
        min_temp: -87,
        max_temp: -22,
        pressure: 872,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '463',
        terrestrial_date: '2014-02-01',
        sol: 530,
        ls: 83,
        season: 'Month 3',
        min_temp: -87,
        max_temp: -28,
        pressure: 873,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '462',
        terrestrial_date: '2014-01-31',
        sol: 529,
        ls: 83,
        season: 'Month 3',
        min_temp: -87,
        max_temp: -23,
        pressure: 875,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '461',
        terrestrial_date: '2014-01-30',
        sol: 528,
        ls: 82,
        season: 'Month 3',
        min_temp: -86,
        max_temp: -26,
        pressure: 876,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '460',
        terrestrial_date: '2014-01-29',
        sol: 527,
        ls: 82,
        season: 'Month 3',
        min_temp: -86,
        max_temp: -23,
        pressure: 877,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '459',
        terrestrial_date: '2014-01-28',
        sol: 526,
        ls: 82,
        season: 'Month 3',
        min_temp: -87,
        max_temp: -24,
        pressure: 878,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '456',
        terrestrial_date: '2014-01-27',
        sol: 525,
        ls: 81,
        season: 'Month 3',
        min_temp: -87,
        max_temp: -29,
        pressure: 878,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '457',
        terrestrial_date: '2014-01-26',
        sol: 524,
        ls: 81,
        season: 'Month 3',
        min_temp: -85,
        max_temp: -27,
        pressure: 880,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '458',
        terrestrial_date: '2014-01-25',
        sol: 523,
        ls: 80,
        season: 'Month 3',
        min_temp: -85,
        max_temp: -25,
        pressure: 881,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '455',
        terrestrial_date: '2014-01-24',
        sol: 522,
        ls: 80,
        season: 'Month 3',
        min_temp: -85,
        max_temp: -26,
        pressure: 881,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '454',
        terrestrial_date: '2014-01-23',
        sol: 521,
        ls: 79,
        season: 'Month 3',
        min_temp: -87,
        max_temp: -26,
        pressure: 882,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '453',
        terrestrial_date: '2014-01-22',
        sol: 520,
        ls: 79,
        season: 'Month 3',
        min_temp: -86,
        max_temp: -24,
        pressure: 884,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '452',
        terrestrial_date: '2014-01-21',
        sol: 519,
        ls: 78,
        season: 'Month 3',
        min_temp: -86,
        max_temp: -25,
        pressure: 884,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '451',
        terrestrial_date: '2014-01-20',
        sol: 518,
        ls: 78,
        season: 'Month 3',
        min_temp: -85,
        max_temp: -29,
        pressure: 885,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '448',
        terrestrial_date: '2014-01-19',
        sol: 517,
        ls: 77,
        season: 'Month 3',
        min_temp: -86,
        max_temp: -27,
        pressure: 885,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '449',
        terrestrial_date: '2014-01-18',
        sol: 516,
        ls: 77,
        season: 'Month 3',
        min_temp: -86,
        max_temp: -25,
        pressure: 888,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '450',
        terrestrial_date: '2014-01-17',
        sol: 515,
        ls: 77,
        season: 'Month 3',
        min_temp: -86,
        max_temp: -23,
        pressure: 888,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '447',
        terrestrial_date: '2014-01-16',
        sol: 514,
        ls: 76,
        season: 'Month 3',
        min_temp: -86,
        max_temp: -29,
        pressure: 888,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '445',
        terrestrial_date: '2014-01-15',
        sol: 513,
        ls: 76,
        season: 'Month 3',
        min_temp: -86,
        max_temp: -29,
        pressure: 889,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '444',
        terrestrial_date: '2014-01-14',
        sol: 512,
        ls: 75,
        season: 'Month 3',
        min_temp: -86,
        max_temp: -24,
        pressure: 890,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '446',
        terrestrial_date: '2014-01-13',
        sol: 511,
        ls: 75,
        season: 'Month 3',
        min_temp: -85,
        max_temp: -31,
        pressure: 892,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '441',
        terrestrial_date: '2014-01-12',
        sol: 510,
        ls: 74,
        season: 'Month 3',
        min_temp: -85,
        max_temp: -31,
        pressure: 892,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '443',
        terrestrial_date: '2014-01-11',
        sol: 509,
        ls: 74,
        season: 'Month 3',
        min_temp: -86,
        max_temp: -30,
        pressure: 895,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '442',
        terrestrial_date: '2014-01-10',
        sol: 508,
        ls: 73,
        season: 'Month 3',
        min_temp: -83,
        max_temp: -29,
        pressure: 893,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '440',
        terrestrial_date: '2014-01-09',
        sol: 507,
        ls: 73,
        season: 'Month 3',
        min_temp: -85,
        max_temp: -25,
        pressure: 894,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '439',
        terrestrial_date: '2014-01-08',
        sol: 506,
        ls: 73,
        season: 'Month 3',
        min_temp: -86,
        max_temp: -27,
        pressure: 894,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '438',
        terrestrial_date: '2014-01-06',
        sol: 505,
        ls: 72,
        season: 'Month 3',
        min_temp: -85,
        max_temp: -29,
        pressure: 895,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '436',
        terrestrial_date: '2014-01-05',
        sol: 504,
        ls: 72,
        season: 'Month 3',
        min_temp: -85,
        max_temp: -29,
        pressure: 895,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '483',
        terrestrial_date: '2014-01-04',
        sol: 503,
        ls: 71,
        season: 'Month 3',
        min_temp: -86,
        max_temp: -28,
        pressure: 897,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '437',
        terrestrial_date: '2014-01-03',
        sol: 502,
        ls: 71,
        season: 'Month 3',
        min_temp: -87,
        max_temp: -30,
        pressure: 898,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
    {
        id: '435',
        terrestrial_date: '2014-01-02',
        sol: 501,
        ls: 70,
        season: 'Month 3',
        min_temp: -86,
        max_temp: -28,
        pressure: 898,
        wind_speed: null,
        atmo_opacity: 'Sunny',
    },
];
