name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  docs-deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Check ref
        if: ${{ github.ref != 'refs/heads/main' }}
        run: |
          echo "It looks like you're trying to execute a workflow not from the main branch."
          exit 1
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Install tsconfig
        run: npm i @gravity-ui/tsconfig
      - name: Install dependencies
        run: npm run docs:deps
      - name: Build
        run: npm run docs:build
      - name: Deploy
        run: npm run docs:deploy
        env:
          GIT_USER: gravity-ui-bot 
          GIT_USER_NAME: gravity-ui-bot
          GIT_USER_EMAIL: 111915794+gravity-ui-bot@users.noreply.github.com
          GIT_PASS: ${{ secrets.GRAVITY_UI_BOT_GITHUB_TOKEN }}
          USE_SSH: false
        
        
        