name: Test documentation deployment

on:
  pull_request:
    branches: [main]

jobs:
  test-docs-deploy:
    name: Test documentation deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Install dependencies
        run: npm run docs:deps
      - name: Test build
        run: npm run docs:build